gems:
- octopress-minify-html

sass:
  style: compressed

minify_html: true

url: "//ctf.tf"
title: "ctf.tf"
description: "A database of collected CTFs and their solutions."
collections:
  ctfs:
    output: true
    permalink: /:collection/:path/
  index:
    output: true
    permalink: /index/:path/
  browse:
    output: true
    permalink: /browse/:path/
    paginate: 20
  latest:
    output: true
    permalink: /latest/:path/
    paginate: 20
  easy:
    output: true
    permalink: /mode/easy/:path/
    paginate: 20
  medium:
    output: true
    permalink: /mode/medium/:path/
    paginate: 20
  hard:
    output: true
    permalink: /mode/hard/:path/
    paginate: 20


defaults:
  - scope:
      path: ""
      type: ctfs
    values:
      layout: ctf
  - scope:
      path: ""
      type: index
    values:
      layout: index
  - scope:
      path: ""
      type: browse
    values:
      layout: browse
  - scope:
      path: ""
      type: latest
    values:
      layout: latest
  - scope:
      path: ""
      type: easy
    values:
      layout: easy
  - scope:
      path: ""
      type: medium
    values:
      layout: medium
  - scope:
      path: ""
      type: hard
    values:
      layout: hard

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      true
  footnote_nr:    1
exclude: [README.md, LICENSE, .git, create_links.sh, remove_links.sh, CNAME, .gitignore]